using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Data.ViewModels;

public class AlertTypeEmployeeViewModel
{
    [Key]
    public int AlertTypeEmployeeID { get; set; }

    public int AlertTypeID { get; set; }

    public int EmployeeID { get; set; }

    public int UserAreaID { get; set; }

    public int? SeverityTypeID { get; set; }

    public int? MaxScore { get; set; }

    public bool SendEmail { get; set; }

    public int CreatedByUserID { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public int? ModifiedByUserID { get; set; }

    public DateTimeOffset? ModifiedDate { get; set; }

    public int? ArchivedByUserID { get; set; }

    public DateTimeOffset? ArchivedDate { get; set; }

    public bool IsAutoGenerated { get; set; }

    public bool IncludeChildLocations { get; set; }

    public bool IncludeChildOrgGroups { get; set; }

    public int? ClassificationTypeID { get; set; }

    // Additional Properties
    public string? CreatedByUserName { get; set; }
    public string? ModifiedByUserName { get; set; }
    public string? ArchivedByUserName { get; set; }
}
