using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.EntityFramework.Models;

[Table("AlertTypeEmployee", Schema = "V7")]
[Index("AlertTypeID", "SeverityTypeID", "ClassificationTypeID", Name = "IX_AlertTypeEmployee_AlertTypeID_SeverityTypeID_ClassificationTypeID_includes")]
public partial class AlertTypeEmployee
{
    [Key]
    public int AlertTypeEmployeeID { get; set; }

    public int AlertTypeID { get; set; }

    public int EmployeeID { get; set; }

    public int UserAreaID { get; set; }

    public int? SeverityTypeID { get; set; }

    public int? MaxScore { get; set; }

    public bool SendEmail { get; set; }

    public int CreatedByUserID { get; set; }

    public DateTimeOffset CreatedDate { get; set; }

    public int? ModifiedByUserID { get; set; }

    public DateTimeOffset? ModifiedDate { get; set; }

    public int? ArchivedByUserID { get; set; }

    public DateTimeOffset? ArchivedDate { get; set; }

    public bool IsAutoGenerated { get; set; }

    public bool IncludeChildLocations { get; set; }

    public bool IncludeChildOrgGroups { get; set; }

    public int? ClassificationTypeID { get; set; }

    [ForeignKey("AlertTypeID")]
    [InverseProperty("AlertTypeEmployees")]
    public virtual AlertType AlertType { get; set; } = null!;

    [InverseProperty("AlertTypeEmployee")]
    public virtual ICollection<AlertTypeEmployeeLocation> AlertTypeEmployeeLocations { get; set; } = new List<AlertTypeEmployeeLocation>();

    [InverseProperty("AlertTypeEmployee")]
    public virtual ICollection<AlertTypeEmployeeOrgGroup> AlertTypeEmployeeOrgGroups { get; set; } = new List<AlertTypeEmployeeOrgGroup>();

    [ForeignKey("ArchivedByUserID")]
    [InverseProperty("AlertTypeEmployeeArchivedByUsers")]
    public virtual User? ArchivedByUser { get; set; }

    [ForeignKey("CreatedByUserID")]
    [InverseProperty("AlertTypeEmployeeCreatedByUsers")]
    public virtual User CreatedByUser { get; set; } = null!;

    [ForeignKey("EmployeeID")]
    [InverseProperty("AlertTypeEmployees")]
    public virtual Employee Employee { get; set; } = null!;

    [ForeignKey("ModifiedByUserID")]
    [InverseProperty("AlertTypeEmployeeModifiedByUsers")]
    public virtual User? ModifiedByUser { get; set; }

    [ForeignKey("SeverityTypeID")]
    [InverseProperty("AlertTypeEmployees")]
    public virtual SeverityType? SeverityType { get; set; }

    [ForeignKey("UserAreaID")]
    [InverseProperty("AlertTypeEmployees")]
    public virtual UserArea UserArea { get; set; } = null!;
}
