CREATE TABLE [V7].[Absence] (
    [AbsenceID]                INT            IDENTITY (1, 1) NOT NULL,
    [EmployeeID]               INT            NOT NULL,
    [AbsenceTypeID]            INT            NOT NULL,
    [AbsenceReasonTypeID]      INT            NULL,
    [OtherAbsenceReason]       NVARCHAR (100) NULL,
    [UserAreaID]               INT            NOT NULL,
    [IsClosed]                 BIT            DEFAULT ((0)) NOT NULL,
    [StartDate]                DATETIMEOFFSET (7) NOT NULL,
    [ExpectedReturnToWorkDate] DATETIMEOFFSET (7) NULL,
    [ActualReturnToWorkDate]   DATETIMEOFFSET (7) NULL,
    [IsAuthorised]             BIT            DEFAULT ((0)) NOT NULL,
    [CreatedByUserID]          INT            NOT NULL,
    [CreatedDate]              DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]         INT            NULL,
    [ModifiedDate]         DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]         INT            NULL,
    [ArchivedDate]             DATETIMEOFFSET (7) NULL,
    [LongTermAbsenceAlertSent] BIT            DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([AbsenceID] ASC),
    CONSTRAINT [FK_Absence_AbsenceReasonType] FOREIGN KEY ([AbsenceReasonTypeID]) REFERENCES [V7].[AbsenceReasonType] ([AbsenceReasonTypeID]),
    CONSTRAINT [FK_Absence_AbsenceType] FOREIGN KEY ([AbsenceTypeID]) REFERENCES [V7].[AbsenceType] ([AbsenceTypeID]),
    CONSTRAINT [FK_Absence_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Absence_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Absence_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_Absence_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Absence_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

