CREATE TABLE [V7].[AccidentCase] (
    [AccidentCaseID]                    INT            IDENTITY (1, 1) NOT NULL,
    [UserAreaID]                        INT            NOT NULL,
    [Reference]                         NVARCHAR (8)   NULL,
    [AdditionalReference]               NVARCHAR (256) NULL,
    [IncidentDate]                      DATETIMEOFFSET (7) NOT NULL,
    [IncidentTime]                      NVARCHAR (15)  NULL,
    [LocationID]                        INT            NULL,
    [OrgGroupID]                        INT            NULL,
    [OptionListItemID]                  INT            NULL,
    [HasLostTime]                       BIT            CONSTRAINT [DF__AccidentC__HasLo__39F939F0] DEFAULT ((0)) NOT NULL,
    [OrganisationName]                  NVARCHAR (255) NULL,
    [LocationTitle]                     NVARCHAR (255) NULL,
    [Address1]                          NVARCHAR (255) NULL,
    [Address2]                          NVARCHAR (255) NULL,
    [Address3]                          NVARCHAR (255) NULL,
    [Town]                              NVARCHAR (255) NULL,
    [County]                            NVARCHAR (255) NULL,
    [PostCode]                          NVARCHAR (20) NULL,
    [Description]                       NVARCHAR (255) NULL,
    [OrgGroupName]                      NVARCHAR (255) NULL,
    [LostDays]                          DECIMAL (8, 2) NULL,
    [ClosedDate]                        DATETIMEOFFSET (7) NULL,
    [ClosedByEmployeeID]                INT            NULL,
    [IsRIDDORReportable]                BIT            CONSTRAINT [DF_AccidentCase_IsRIDDORReportable] DEFAULT ((0)) NOT NULL,
    [RootCauseTypeID]                   INT            NULL,
    [SeverityTypeID]                    INT            NULL,
    [InjuryTypeID]                      INT            NULL,
    [IncidentKindID]                    INT            NULL,
    [IsReadyToClose]                    BIT            CONSTRAINT [DF__AccidentC__IsRea__2FDB9E30] DEFAULT ((0)) NOT NULL,
    [ManagerEmployeeID]                 INT            NULL,
    [HasSuppressedAlerts]               BIT            DEFAULT ((0)) NOT NULL,
    [BodyPartID]                        INT            NULL,
    [IsFatality]                        BIT            DEFAULT ((0)) NOT NULL,
    [IsRIDDORSpecifiedInjury]           BIT            DEFAULT ((0)) NOT NULL,
    [IsUnableToWorkForAbove7Days]       BIT            DEFAULT ((0)) NOT NULL,
    [IsNonWorkerInjuredAndHospitalised] BIT            DEFAULT ((0)) NOT NULL,
    [IsAnonymousSubmission]             BIT            DEFAULT ((0)) NOT NULL,
    [IsApprovedSubmission]              BIT            DEFAULT ((1)) NOT NULL,
    [HasBeenHospitalisedForOver1Day]    BIT            DEFAULT ((0)) NOT NULL,
    [HasInvolvedUnconsciousness]        BIT            DEFAULT ((0)) NOT NULL,
    [HasInvolvedResuscitation]          BIT            DEFAULT ((0)) NOT NULL,
    [HasInvolvedEmergencyServices]      BIT            DEFAULT ((0)) NOT NULL,
    [IsWorkRelatedIncident]             BIT            DEFAULT ((0)) NOT NULL,
    [ManagerEmployeeEmail]              NVARCHAR (255) NULL,
    [PortalAccessToken]                 NVARCHAR (20)  NULL,
    [IsRIDDORDangerousOccurrence]       BIT            DEFAULT ((0)) NOT NULL,
    [IsRIDDOROccupationalDisease]       BIT            DEFAULT ((0)) NOT NULL,
    [IsSignOffRequired]                 BIT            DEFAULT ((0)) NOT NULL,
    [IsSignedOff]                       BIT            DEFAULT ((0)) NOT NULL,
    [RootCauseOther]                    NVARCHAR (100) NULL,
    [RootCauseCategoryTypeID]           INT            NULL,
    [IncidentDateTimeZoneID]            INT            DEFAULT ((0)) NULL,
    [IsFirstAidRefused]                 BIT            DEFAULT ((0)) NOT NULL,
    [FirstAidRefuserSignature]          NVARCHAR (MAX) NULL,
    [CreatedByUserID]                   INT            NOT NULL,
    [CreatedDate]                       DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]              INT            NULL,
    [ModifiedDate]                  DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                  INT            NULL,
    [ArchivedDate]                      DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK__Accident__342FD46B4D8C5C8C] PRIMARY KEY CLUSTERED ([AccidentCaseID] ASC),
    CONSTRAINT [FK_AccidentCase_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AccidentCase_BodyPart] FOREIGN KEY ([BodyPartID]) REFERENCES [V7].[BodyPart] ([BodyPartID]),
    CONSTRAINT [FK_AccidentCase_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AccidentCase_Employee] FOREIGN KEY ([ClosedByEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_AccidentCase_IncidentDateTimeZone] FOREIGN KEY ([IncidentDateTimeZoneID]) REFERENCES [V7].[BSSTimeZone] ([TimeZoneID]),
    CONSTRAINT [FK_AccidentCase_IncidentKind] FOREIGN KEY ([IncidentKindID]) REFERENCES [V7].[IncidentKind] ([IncidentKindID]),
    CONSTRAINT [FK_AccidentCase_InjuryType] FOREIGN KEY ([InjuryTypeID]) REFERENCES [V7].[InjuryType] ([InjuryTypeID]),
    CONSTRAINT [FK_AccidentCase_LocationID] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_AccidentCase_ManagerEmployee] FOREIGN KEY ([ManagerEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_AccidentCase_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AccidentCase_OptionListItemID] FOREIGN KEY ([OptionListItemID]) REFERENCES [V7].[OptionListItem] ([OptionListItemID]),
    CONSTRAINT [FK_AccidentCase_OrgGroupID] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_AccidentCase_RootCauseCategoryTypeID] FOREIGN KEY ([RootCauseCategoryTypeID]) REFERENCES [V7].[RootCauseCategoryType] ([RootCauseCategoryTypeID]),
    CONSTRAINT [FK_AccidentCase_RootCauseTypeID] FOREIGN KEY ([RootCauseTypeID]) REFERENCES [V7].[RootCauseType] ([RootCauseTypeID]),
    CONSTRAINT [FK_AccidentCase_SeverityType] FOREIGN KEY ([SeverityTypeID]) REFERENCES [V7].[SeverityType] ([SeverityTypeID]),
    CONSTRAINT [FK_AccidentCase_UserAreaID] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);


GO
CREATE NONCLUSTERED INDEX [IX_AccidentCase_UserAreaID_ArchivedDate_LocationID_OrgGroupID]
    ON [V7].[AccidentCase]([UserAreaID] ASC, [ArchivedDate] ASC, [LocationID] ASC, [OrgGroupID] ASC);

