CREATE TABLE [V7].[AccidentPerson] (
    [AccidentPersonID]           INT             IDENTITY (1, 1) NOT NULL,
    [AccidentPersonTypeID]       INT             NULL,
    [AccidentCaseID]             INT             NULL,
    [EmployeeID]                 INT             NULL,
    [EmploymentStatusTypeID]     INT             NULL,
    [UserAreaID]                 INT             NOT NULL,
    [LocationID]                 INT             NULL,
    [Email]                      NVARCHAR (255)  NULL,
    [GenderTypeID]               INT             NULL,
    [Telephone]                  NVARCHAR (255)  NULL,
    [Mobile]                     NVARCHAR (255)  NULL,
    [Age]                        INT             NULL,
    [NINumber]                   NVARCHAR (10)   NULL,
    [MaritalStatusTypeID]        INT             NULL,
    [DateEmploymentStarted]      DATETIMEOFFSET (7) NULL,
    [NumberOfDependents]         INT             NULL,
    [AverageEarningPerWeek]      INT             NULL,
    [SickPayRate]                INT             NULL,
    [MaximumEntitledPeriod]      INT             NULL,
    [IsInjuryResultedInDeath]    BIT             NULL,
    [IsInvolvedInjury]           BIT             NULL,
    [IsMedicalAttentionRequired] BIT             NULL,
    [IsPeventedFromWork]         BIT             NULL,
    [DaysOffWork]                INT             NULL,
    [IsBecameUnconscious]        BIT             NULL,
    [IsRequiredResuscitation]    BIT             NULL,
    [InHostpitalMoreThan24Hours] BIT             NULL,
    [IsLossOfSight]              BIT             NULL,
    [InjuryDescription]          NVARCHAR (2000) NULL,
    [OrgGroupID]                 INT             NULL,
    [ParentID]                   INT             NULL,
    [SeverityOfInjuryTypeID]     INT             NULL,
    [InjuryTypeID]               INT             NULL,
    [AssessorEmployeeID]         INT             NULL,
    [AssessorLocationID]         INT             NULL,
    [AssessorEmail]              NVARCHAR (255)  NULL,
    [AssessorOrgGroupID]         INT             NULL,
    [WasFirstAidAdministered]    BIT             NULL,
    [FirstAidAttachmentID]       INT             NULL,
    [CreatedByUserID]            INT             NOT NULL,
    [CreatedDate]                DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]           INT             NULL,
    [ArchivedByUserID]           INT             NULL,
    [Title] VARCHAR (20) NULL,
    [FirstName] VARCHAR (100) NULL,
    [FamilyName] VARCHAR (100) NULL,
    [LocationTitle] NVARCHAR (255) NULL,
    [Address1] NVARCHAR (255) NULL,
    [Address2] NVARCHAR (255) NULL,
    [Address3] NVARCHAR (255) NULL,
    [Town] NVARCHAR (255) NULL,
    [County] NVARCHAR (255) NULL,
    [PostCode] NVARCHAR (20) NULL,
    [JobTitle] NVARCHAR (255) NULL,
    [AssessorTitle] NVARCHAR (20) NULL,
    [AssessorFirstName] NVARCHAR (100) NULL,
    [AssessorFamilyName] NVARCHAR (100) NULL,
    [AssessorLocationTitle] NVARCHAR (255) NULL,
    [AssessorAddress1] NVARCHAR (255) NULL,
    [AssessorAddress2] NVARCHAR (255) NULL,
    [AssessorAddress3] NVARCHAR (255) NULL,
    [AssessorTown] NVARCHAR (255) NULL,
    [AssessorCounty] NVARCHAR (255) NULL,
    [AssessorPostCode] NVARCHAR (20) NULL,
    [FirstAidApplied] NVARCHAR (MAX) NULL,
    [ModifiedDate] DATETIMEOFFSET (7) NULL,
    [ArchivedDate] DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK__tmp_ms_x__E61B83B8AF7F6C5B] PRIMARY KEY CLUSTERED ([AccidentPersonID] ASC),
    CONSTRAINT [FK_AccidentPerson_AccidentCase] FOREIGN KEY ([AccidentCaseID]) REFERENCES [V7].[AccidentCase] ([AccidentCaseID]),
    CONSTRAINT [FK_AccidentPerson_AccidentPersonID] FOREIGN KEY ([ParentID]) REFERENCES [V7].[AccidentPerson] ([AccidentPersonID]),
    CONSTRAINT [FK_AccidentPerson_AccidentPersonType] FOREIGN KEY ([AccidentPersonTypeID]) REFERENCES [V7].[AccidentPersonType] ([AccidentPersonTypeID]),
    CONSTRAINT [FK_AccidentPerson_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AccidentPerson_AssessorEmployeeID] FOREIGN KEY ([AssessorEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_AccidentPerson_AssessorLocationID] FOREIGN KEY ([AssessorLocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_AccidentPerson_AssessorOrgGroupID] FOREIGN KEY ([AssessorOrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_AccidentPerson_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AccidentPerson_EmployeeID] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_AccidentPerson_EmploymentStatusTypeID] FOREIGN KEY ([EmploymentStatusTypeID]) REFERENCES [V7].[EmploymentStatusType] ([EmploymentStatusTypeID]),
    CONSTRAINT [FK_AccidentPerson_GenderTypeID] FOREIGN KEY ([GenderTypeID]) REFERENCES [V7].[GenderType] ([GenderTypeID]),
    CONSTRAINT [FK_AccidentPerson_InjuryTypeID] FOREIGN KEY ([InjuryTypeID]) REFERENCES [V7].[InjuryType] ([InjuryTypeID]),
    CONSTRAINT [FK_AccidentPerson_LocationID] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_AccidentPerson_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AccidentPerson_OrgGroupID] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_AccidentPerson_SeverityOfInjuryTypeID] FOREIGN KEY ([SeverityOfInjuryTypeID]) REFERENCES [V7].[SeverityOfInjuryType] ([SeverityOfInjuryTypeID]),
    CONSTRAINT [FK_AccidentPerson_UserAreaID] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

