CREATE TABLE [V7].[AlertTypeEmployee] (
    [AlertTypeEmployeeID]   INT      IDENTITY (1, 1) NOT NULL,
    [AlertTypeID]           INT      NOT NULL,
    [EmployeeID]            INT      NOT NULL,
    [UserAreaID]            INT      NOT NULL,
    [SeverityTypeID]        INT      NULL,
    [MaxScore]              INT      NULL,
    [SendEmail]             BIT      CONSTRAINT [DF_AlertTypeEmployee_SendEmail] DEFAULT ((0)) NOT NULL,
    [CreatedByUserID]       INT      NOT NULL,
    [CreatedDate]           DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]  INT      NULL,
    [ModifiedDate]      DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]      INT      NULL,
    [ArchivedDate]          DATETIMEOFFSET (7) NULL,
    [IsAutoGenerated]       BIT      DEFAULT ((0)) NOT NULL,
    [IncludeChildLocations] BIT      DEFAULT ((0)) NOT NULL,
    [IncludeChildOrgGroups] BIT      DEFAULT ((0)) NOT NULL,
    [ClassificationTypeID]  INT      NULL,
    CONSTRAINT [PK__AlertTyp__C037332056983FA9] PRIMARY KEY CLUSTERED ([AlertTypeEmployeeID] ASC),
    CONSTRAINT [FK_AlertTypeEmployee_AlertType] FOREIGN KEY ([AlertTypeID]) REFERENCES [V7].[AlertType] ([AlertTypeID]),
    CONSTRAINT [FK_AlertTypeEmployee_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AlertTypeEmployee_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AlertTypeEmployee_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_AlertTypeEmployee_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AlertTypeEmployee_SeverityType] FOREIGN KEY ([SeverityTypeID]) REFERENCES [V7].[SeverityType] ([SeverityTypeID]),
    CONSTRAINT [FK_AlertTypeEmployee_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);


GO
CREATE NONCLUSTERED INDEX [IX_AlertTypeEmployee_AlertTypeID_SeverityTypeID_ClassificationTypeID_includes]
    ON [V7].[AlertTypeEmployee]([AlertTypeID] ASC, [SeverityTypeID] ASC, [ClassificationTypeID] ASC)
    INCLUDE([EmployeeID], [UserAreaID], [MaxScore], [SendEmail], [CreatedByUserID], [CreatedDate], [ModifiedByUserID], [ModifiedDate], [ArchivedDate], [IsAutoGenerated], [IncludeChildLocations], [IncludeChildOrgGroups]);

