CREATE TABLE [V7].[AssetInspection] (
    [AssetInspectionID]              INT            IDENTITY (1, 1) NOT NULL,
    [AssetInspectionCategoryID]      INT            NOT NULL,
    [AssetID]                        INT            NOT NULL,
    [UserAreaID]                     INT            NOT NULL,
    [UserAreaDivisionID]             INT            NULL,
    [Reference]                      NVARCHAR (50)  NULL,
    [InspectionDate]                 DATETIMEOFFSET (7) NOT NULL,
    [InspectorEmployeeID]            INT            NULL,
    [InspectorName]                  NVARCHAR (255) NULL,
    [InspectorCompanyName]           NVARCHAR (255) NULL,
    [LocationID]                     INT            NULL,
    [OrgGroupID]                     INT            NULL,
    [Notes]                          NVARCHAR (MAX) NULL,
    [CreatedByUserID]                INT            NOT NULL,
    [CreatedDate]                    DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]           INT            NULL,
    [ModifiedDate]               DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]               INT            NULL,
    [ArchivedDate]                   DATETIMEOFFSET (7) NULL,
    [QuestionnaireResponseID]        INT            NULL,
    [SeriousDefects]                 NVARCHAR (MAX) NULL,
    [OtherDefects]                   NVARCHAR (MAX) NULL,
    [AssetInspectionCrimsonImportID] INT            NULL,
    [HasFailed]                      BIT            NOT NULL,
    [Observations]                   NVARCHAR (MAX) NULL,
    [AssetInspectionStatusTypeID]    INT            NULL,
    PRIMARY KEY CLUSTERED ([AssetInspectionID] ASC)
);

