CREATE TABLE [V7].[AssetInspectionCrimsonImportFailure] (
    [AssetInspectionCrimsonImportFailureID] INT            IDENTITY (1, 1) NOT NULL,
    [AssetInspectionCrimsonImportID]        INT            NOT NULL,
    [CrimsonRecordID]                       NVARCHAR (20)  NOT NULL,
    [CrimsonReportID]                       NVARCHAR (20)  NOT NULL,
    [UserAreaID]                            INT            NOT NULL,
    [MatchingAssetID]                       INT            NULL,
    [MatchingLocationID]                    INT            NULL,
    [IsProcessed]                           BIT            DEFAULT ((0)) NOT NULL,
    [Notes]                                 NVARCHAR (MAX) NULL,
    [CreatedByUserID]                       INT            NOT NULL,
    [CreatedDate]                           DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]                  INT            NULL,
    [ModifiedDate]                      DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                      INT            NULL,
    [ArchivedDate]                          DATETIMEOFFSET (7) NULL,
    [AssetInspectionStatusTypeID]           INT            NULL,
    PRIMARY KEY CLUSTERED ([AssetInspectionCrimsonImportFailureID] ASC),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_Asset] FOREIGN KEY ([MatchingAssetID]) REFERENCES [V7].[Asset] ([AssetID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_AssetInspectionCrimsonImport] FOREIGN KEY ([AssetInspectionCrimsonImportID]) REFERENCES [V7].[AssetInspectionCrimsonImport] ([AssetInspectionCrimsonImportID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_AssetInspectionStatusType] FOREIGN KEY ([AssetInspectionStatusTypeID]) REFERENCES [V7].[AssetInspectionStatusType] ([AssetInspectionStatusTypeID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_Location] FOREIGN KEY ([MatchingLocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_AssetInspectionCrimsonImportFailure_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

