CREATE TABLE [V7].[Asset] (
    [AssetID]                  INT             IDENTITY (1, 1) NOT NULL,
    [AssetCategoryID]          INT             NOT NULL,
    [AssetStatusTypeID]        INT             NOT NULL,
    [UserAreaID]               INT             NOT NULL,
    [UserAreaDivisionID]       INT             NULL,
    [ExpirationTaskScheduleID] INT             NULL,
    [Reference]                NVARCHAR (255)  NULL,
    [Title]                    NVARCHAR (255)  NOT NULL,
    [Description]              NVARCHAR (MAX)  NULL,
    [Notes]                    NVARCHAR (MAX)  NULL,
    [SerialNumber]             NVARCHAR (50)   NULL,
    [MakeModel]                NVARCHAR (50)   NULL,
    [OrderNumber]              NVARCHAR (50)   NULL,
    [SupplierBookedDate]       DATETIMEOFFSET (7) NULL,
    [IsLive]                   BIT             NOT NULL,
    [ExpiryDate]               DATETIMEOFFSET (7) NULL,
    [PurchaseDate]             DATETIMEOFFSET (7) NULL,
    [InstallationDate]         DATETIMEOFFSET (7) NULL,
    [CurrencyTypeID]           INT             NOT NULL,
    [InitialCost]              NUMERIC (10, 2) NULL,
    [CurrentCost]              NUMERIC (10, 2) NULL,
    [DepreciationCost]         NUMERIC (10, 2) NULL,
    [PurchaserEmployeeID]      INT             NULL,
    [AssigneeEmployeeID]       INT             NULL,
    [ManufacturerName]         NVARCHAR (100)  NULL,
    [SupplierID]               INT             NULL,
    [CreatedByUserID]          INT             NOT NULL,
    [CreatedDate]              DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]     INT             NULL,
    [ModifiedDate]         DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]         INT             NULL,
    [ArchivedDate]             DATETIMEOFFSET (7) NULL,
    [IsForDSE]                 BIT             NOT NULL,
    PRIMARY KEY CLUSTERED ([AssetID] ASC)
);

