CREATE TABLE [V7].[Case] (
    [CaseID]               INT            IDENTITY (1, 1) NOT NULL,
    [ParentID]             INT            NULL,
    [Reference]            NVARCHAR (50)  NULL,
    [Title]                NVARCHAR (255) NOT NULL,
    [Description]          NVARCHAR (MAX) NULL,
    [UserAreaID]           INT            NOT NULL,
    [CaseStatusTypeID]     INT            NOT NULL,
    [CaseTypeID]           INT            NOT NULL,
    [TaskSeverityID]       INT            NOT NULL,
    [DueDate]              DATETIMEOFFSET (7) NULL,
    [ClosedDate]           DATETIMEOFFSET (7) NULL,
    [CreatedByUserID]      INT            NOT NULL,
    [CreatedDate]          DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID] INT            NULL,
    [ModifiedDate]     DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]     INT            NULL,
    [ArchivedDate]         DATETIMEOFFSET (7) NULL,
    [PercentageComplete]   TINYINT        DEFAULT ((0)) NOT NULL,
    [IsPrivate]            BIT            DEFAULT ((0)) NOT NULL,
    [UserAreaDivisionID]   INT            NULL,
    PRIMARY KEY CLUSTERED ([CaseID] ASC),
    CONSTRAINT [FK_Case_ArchivedByUser] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Case_CaseStatusType] FOREIGN KEY ([CaseStatusTypeID]) REFERENCES [V7].[CaseStatusType] ([CaseStatusTypeID]),
    CONSTRAINT [FK_Case_CaseType] FOREIGN KEY ([CaseTypeID]) REFERENCES [V7].[CaseType] ([CaseTypeID]),
    CONSTRAINT [FK_Case_CreatedByUser] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Case_ModifiedByUser] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Case_Parent] FOREIGN KEY ([ParentID]) REFERENCES [V7].[Case] ([CaseID]),
    CONSTRAINT [FK_Case_TaskSeverity] FOREIGN KEY ([TaskSeverityID]) REFERENCES [V7].[TaskSeverity] ([TaskSeverityID]),
    CONSTRAINT [FK_Case_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [FK_Case_UserAreaDivision] FOREIGN KEY ([UserAreaDivisionID]) REFERENCES [V7].[UserAreaDivision] ([UserAreaDivisionID]),
    UNIQUE NONCLUSTERED ([Reference] ASC)
);

