CREATE TABLE [V7].[Company] (
    [CompanyID]            INT            IDENTITY (1, 1) NOT NULL,
    [UserAreaID]           INT            NOT NULL,
    [Name]                 NVARCHAR (MAX) NOT NULL,
    [CompanyStatusID]      INT            NOT NULL,
    [LocationID]           INT            NOT NULL,
    [Email]                NVARCHAR (255) NULL,
    [OrgGroupID]           INT            NULL,
    [MainIndustryTypeID]   INT            NOT NULL,
    [MainActivityTypeID]   INT            NOT NULL,
    [SubActivityTypeID]    INT            NOT NULL,
    [CreatedByUserID]      INT            NOT NULL,
    [CreatedDate]          DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]     INT            NULL,
    [ModifiedDate]     DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]     INT            NULL,
    [ArchivedDate]         DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([CompanyID] ASC),
    CONSTRAINT [FK_Company_ArchivedByUserID] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Company_CompanyStatusID] FOREIGN KEY ([CompanyStatusID]) REFERENCES [V7].[CompanyStatus] ([CompanyStatusID]),
    CONSTRAINT [FK_Company_CreatedByUserID] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Company_ModifiedByUserID] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Company_MainActivityTypeID] FOREIGN KEY ([MainActivityTypeID]) REFERENCES [V7].[MainActivityType] ([MainActivityTypeID]),
    CONSTRAINT [FK_Company_MainIndustryTypeID] FOREIGN KEY ([MainIndustryTypeID]) REFERENCES [V7].[MainIndustryType] ([MainIndustryTypeID]),
    CONSTRAINT [FK_Company_OrgGroupID] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_Company_SubActivityTypeID] FOREIGN KEY ([SubActivityTypeID]) REFERENCES [V7].[SubActivityType] ([SubActivityTypeID]),
    CONSTRAINT [FK_Company_UserAreaID] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

