CREATE TABLE [V7].[ContractorCompetency] (
    [ContractorCompetencyID]           INT            IDENTITY (1, 1) NOT NULL,
    [UserAreaID]                       INT            NOT NULL,
    [ContractorCompanyID]              INT            NULL,
    [EmployeeID]                       INT            NULL,
    [CompetencyID]                     INT            NOT NULL,
    [TemplateContractorCompetencyID]   INT            NULL,
    [IsInPlace]                        BIT            NULL,
    [IsExempt]                         BIT            DEFAULT ((0)) NOT NULL,
    [ExemptionToDate]                  DATETIMEOFFSET (7) NULL,
    [ValidToDate]                      DATETIMEOFFSET (7) NULL,
    [Comments]                         NVARCHAR (MAX) NULL,
    [CreatedByUserID]                  INT            NOT NULL,
    [CreatedDate]                      DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]                 INT            NULL,
    [ModifiedDate]                 DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                 INT            NULL,
    [ArchivedDate]                     DATETIMEOFFSET (7) NULL,
    [ContractorCompetencyStatusTypeID] INT            NULL,
    [IsOptional]                       BIT            DEFAULT ((0)) NOT NULL,
    [IsEvidenceMandatory]              BIT            DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ContractorCompetencyID] ASC),
    CONSTRAINT [FK_ContractorCompetency_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_ContractorCompetency_Comptency] FOREIGN KEY ([CompetencyID]) REFERENCES [V7].[Competency] ([CompetencyID]),
    CONSTRAINT [FK_ContractorCompetency_ContractorCompany] FOREIGN KEY ([ContractorCompanyID]) REFERENCES [V7].[ContractorCompany] ([ContractorCompanyID]),
    CONSTRAINT [FK_ContractorCompetency_ContractorCompetencyStatusType] FOREIGN KEY ([ContractorCompetencyStatusTypeID]) REFERENCES [V7].[ContractorCompetencyStatusType] ([ContractorCompetencyStatusTypeID]),
    CONSTRAINT [FK_ContractorCompetency_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_ContractorCompetency_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_ContractorCompetency_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_ContractorCompetency_TemplateContractorCompetency] FOREIGN KEY ([TemplateContractorCompetencyID]) REFERENCES [V7].[ContractorCompetency] ([ContractorCompetencyID]),
    CONSTRAINT [FK_ContractorCompetency_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

