CREATE TABLE [V7].[Contact] (
    [ContactID]            INT            IDENTITY (1, 1) NOT NULL,
    [EmployeeID]           INT            NULL,
    [UserAreaID]           INT            NOT NULL,
    [PersonTitleTypeID]    INT            NULL,
    [ContactTypeID]        INT            NULL,
    [Name]                 NVARCHAR (255) NOT NULL,
    [Email]                NVARCHAR (255) NULL,
    [HomeAddressID]        INT            NULL,
    [Telephone]            NVARCHAR (255) NULL,
    [Mobile]               NVARCHAR (255) NULL,
    [LinkedInURL]          NVARCHAR (255) NULL,
    [Relationship]         NVARCHAR (255) NULL,
    [CreatedByUserID]      INT            NOT NULL,
    [CreatedDate]          DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]     INT            NULL,
    [ModifiedDate]     DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]     INT            NULL,
    [ArchivedDate]         DATETIMEOFFSET (7) NULL,
    [Telephone2]           NVARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ContactID] ASC),
    CONSTRAINT [FK_Contact_Address] FOREIGN KEY ([HomeAddressID]) REFERENCES [V7].[Address] ([AddressID]),
    CONSTRAINT [FK_Contact_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Contact_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Contact_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_Contact_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Contact_PersonTitleType] FOREIGN KEY ([PersonTitleTypeID]) REFERENCES [V7].[PersonTitleType] ([PersonTitleTypeID]),
    CONSTRAINT [FK_Contact_UserAreaID] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

