CREATE TABLE [V7].[ContractorCompany] (
    [ContractorCompanyID]              INT            IDENTITY (1, 1) NOT NULL,
    [UserAreaID]                       INT            NOT NULL,
    [Name]                             NVARCHAR (256) NOT NULL,
    [AddressID]                        INT            NOT NULL,
    [PhoneNumber]                      NVARCHAR (50)  NULL,
    [ContractorCategoryID]             INT            NOT NULL,
    [Status]                           INT            NOT NULL,
    [Notes]                            NVARCHAR (MAX) NULL,
    [CreatedByUserID]                  INT            NOT NULL,
    [CreatedDate]                      DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]                 INT            NULL,
    [ModifiedDate]                 DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                 INT            NULL,
    [ArchivedDate]                     DATETIMEOFFSET (7) NULL,
    [ContactName]                      NVARCHAR (150) NULL,
    [ContactEmail]                     NVARCHAR (255) NULL,
    [WebsiteURL]                       NVARCHAR (255) NULL,
    [IsCompliantCachedValue]           BIT            DEFAULT ((0)) NOT NULL,
    [IsBlacklisted]                    BIT            DEFAULT ((0)) NOT NULL,
    [BlacklistedReason]                NVARCHAR (255) NULL,
    [DefaultChecklistID]               INT            NULL,
    [CompletedQuestionnaireResponseID] INT            NULL,
    [AllowSignInWhenNonCompliant]      BIT            DEFAULT ((0)) NOT NULL,
    [ContractorTypeID]                 INT            NULL,
    [IsBranch]                         BIT            DEFAULT ((0)) NOT NULL,
    [IsSignedOff]                      BIT            DEFAULT ((0)) NOT NULL,
    [HasSubContractors]                BIT            DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ContractorCompanyID] ASC),
    CONSTRAINT [FK_ContractorCompany_Address] FOREIGN KEY ([AddressID]) REFERENCES [V7].[Address] ([AddressID]),
    CONSTRAINT [FK_ContractorCompany_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_ContractorCompany_Checklist] FOREIGN KEY ([DefaultChecklistID]) REFERENCES [V7].[Checklist] ([ChecklistID]),
    CONSTRAINT [FK_ContractorCompany_ContractorCategory] FOREIGN KEY ([ContractorCategoryID]) REFERENCES [V7].[ContractorCategory] ([ContractorCategoryID]),
    CONSTRAINT [FK_ContractorCompany_ContractorType] FOREIGN KEY ([ContractorTypeID]) REFERENCES [V7].[ContractorType] ([ContractorTypeID]),
    CONSTRAINT [FK_ContractorCompany_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_ContractorCompany_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_ContractorCompany_QuestionnaireResponse] FOREIGN KEY ([CompletedQuestionnaireResponseID]) REFERENCES [V7].[QuestionnaireResponse] ([QuestionnaireResponseID]),
    CONSTRAINT [FK_ContractorCompany_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

