CREATE TABLE [V7].[Employee] (
    [EmployeeID]            INT                IDENTITY (1, 1) NOT NULL,
    [UserAreaID]            INT                NOT NULL,
    [PersonTitleType]       VARCHAR (20)       NULL,
    [GenderType]            VARCHAR (20)       NULL,
    [Reference]             NVARCHAR (255)     NULL,
    [Name]                  NVARCHAR (255)     NOT NULL,
    [Email]                 NVARCHAR (255)     NULL,
    [UserID]                INT                NULL,
    [IsHidden]              BIT                DEFAULT ((0)) NOT NULL,
    [IsGloballyViewable]    BIT                DEFAULT ((0)) NOT NULL,
    [IsArchivableViaImport] BIT                DEFAULT ((0)) NOT NULL,
    [IsHomeWorker]          BIT                DEFAULT ((0)) NOT NULL,
    [IsNotWorking]          BIT                DEFAULT ((0)) NOT NULL,
    [IsComputerUser]        BIT                DEFAULT ((0)) NOT NULL,
    [HasEmailsDisabled]     BIT                DEFAULT ((0)) NOT NULL,
    [DateOfBirth]           DATE               NULL,
    [StartDate]             DATE               NULL,
    [EndDate]               DATE               NULL,
    [AnnualReviewDate]      DATE               NULL,
    [NINumber]              NVARCHAR (50)      NULL,
    [JobTitle]              NVARCHAR (255)     NULL,
    [Telephone]             NVARCHAR (255)     NULL,
    [Mobile]                NVARCHAR (255)     NULL,
    [LineManagerEmployeeID] INT                NULL,
    [ProfileAttachmentID]   INT                NULL,
    [Signature]             NVARCHAR (MAX)     NULL,
    [CreatedByUserID]       INT                NOT NULL,
    [CreatedDate]           DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]  INT                NULL,
    [ModifiedDate]      DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]      INT                NULL,
    [ArchivedDate]          DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([EmployeeID] ASC),
    CONSTRAINT [FK_Employee_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Employee_Attachment] FOREIGN KEY ([ProfileAttachmentID]) REFERENCES [V7].[Attachment] ([AttachmentID]),
    CONSTRAINT [FK_Employee_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Employee_LineManagerEmployee] FOREIGN KEY ([LineManagerEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_Employee_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Employee_User] FOREIGN KEY ([UserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Employee_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

