CREATE TABLE [V7].[HazardReport] (
    [HazardReportID]         INT            IDENTITY (1, 1) NOT NULL,
    [HazardReportTypeID]     INT            NULL,
    [LocationID]             INT            NULL,
    [TaskID]                 INT            NULL,
    [UserAreaID]             INT            NOT NULL,
    [Description]            NVARCHAR (MAX) NOT NULL,
    [SeverityTitle]          NVARCHAR (50)  NULL,
    [IsReportedAnonymously]  BIT            DEFAULT ((0)) NOT NULL,
    [ReportedDate]           DATETIMEOFFSET (7) NOT NULL,
    [CreatedByUserID]        INT            NOT NULL,
    [CreatedDate]            DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]   INT            NULL,
    [ModifiedDate]       DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]       INT            NULL,
    [ArchivedDate]           DATETIMEOFFSET (7) NULL,
    [HazardStatusID]         INT            NULL,
    [ReporterType]           NVARCHAR (100) NULL,
    [ReporterName]           NVARCHAR (150) NULL,
    [ReporterContactDetails] NVARCHAR (150) NULL,
    PRIMARY KEY CLUSTERED ([HazardReportID] ASC),
    CONSTRAINT [FK_HazardReport_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HazardReport_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HazardReport_HazardReportType] FOREIGN KEY ([HazardReportTypeID]) REFERENCES [V7].[HazardReportType] ([HazardReportTypeID]),
    CONSTRAINT [FK_HazardReport_Location] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_HazardReport_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HazardReport_Task] FOREIGN KEY ([TaskID]) REFERENCES [V7].[BSSTask] ([TaskID]),
    CONSTRAINT [FK_HazardReport_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

