CREATE TABLE [V7].[HRCaseMeeting] (
    [HRCaseMeetingID]                       INT            IDENTITY (1, 1) NOT NULL,
    [HRCaseID]                              INT            NOT NULL,
    [HRMeetingTypeID]                       INT            NOT NULL,
    [HRCaseStatusTypeID]                    INT            NULL,
    [MeetingDate]                           DATETIMEOFFSET (7) NOT NULL,
    [Status]                                SMALLINT       NULL,
    [Location]                              NVARCHAR (255) NULL,
    [IsFirstInstance]                       BIT            DEFAULT ((0)) NOT NULL,
    [IsComplete]                            BIT            DEFAULT ((0)) NOT NULL,
    [IsAdjourned]                           BIT            DEFAULT ((0)) NOT NULL,
    [IsEditEnabled]                         BIT            DEFAULT ((0)) NOT NULL,
    [ManagerEmployeeID]                     INT            NULL,
    [EmployeeSignature]                     NVARCHAR (MAX) NULL,
    [EmployeeSignDate]                      DATETIMEOFFSET (7) NULL,
    [ManagerSignature]                      NVARCHAR (MAX) NULL,
    [ManagerSignDate]                       DATETIMEOFFSET (7) NULL,
    [AddedToBundleDate]                     DATETIMEOFFSET (7) NULL,
    [HasProvidedSelfAssessment]             BIT            NULL,
    [SelfAssessmentQuestionnaireResponseID] INT            NULL,
    [SelfAssessmentAttachmentID]            INT            NULL,
    [CreatedByUserID]                       INT            NOT NULL,
    [CreatedDate]                           DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]                  INT            NULL,
    [ModifiedDate]                      DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                      INT            NULL,
    [ArchivedDate]                          DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([HRCaseMeetingID] ASC),
    CONSTRAINT [FK_HRCaseMeeting_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCaseMeeting_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCaseMeeting_HRCase] FOREIGN KEY ([HRCaseID]) REFERENCES [V7].[HRCase] ([HRCaseID]),
    CONSTRAINT [FK_HRCaseMeeting_HRCaseStatusType] FOREIGN KEY ([HRCaseStatusTypeID]) REFERENCES [V7].[HRCaseStatusType] ([HRCaseStatusTypeID]),
    CONSTRAINT [FK_HRCaseMeeting_HRMeetingType] FOREIGN KEY ([HRMeetingTypeID]) REFERENCES [V7].[HRMeetingType] ([HRMeetingTypeID]),
    CONSTRAINT [FK_HRCaseMeeting_ManagerEmployee] FOREIGN KEY ([ManagerEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_HRCaseMeeting_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCaseMeeting_SAAttachment] FOREIGN KEY ([SelfAssessmentAttachmentID]) REFERENCES [V7].[Attachment] ([AttachmentID]),
    CONSTRAINT [FK_HRCaseMeeting_SAQuestionnaireResponse] FOREIGN KEY ([SelfAssessmentQuestionnaireResponseID]) REFERENCES [V7].[QuestionnaireResponse] ([QuestionnaireResponseID])
);

