CREATE TABLE [V7].[HRCase] (
    [HRCaseID]                           INT             IDENTITY (1, 1) NOT NULL,
    [HRTypeID]                           INT             NOT NULL,
    [HRCategoryID]                       INT             NULL,
    [HRCategoryOther]                    NVARCHAR (50)   NULL,
    [HRCaseStatusTypeID]                 INT             NOT NULL,
    [SeverityGenericStatusTypeID]        INT             NULL,
    [UserAreaID]                         INT             NOT NULL,
    [EmployeeID]                         INT             NULL,
    [Reference]                          NVARCHAR (255)  NULL,
    [Description]                        NVARCHAR (2000) NULL,
    [OpenedDate]                         DATETIMEOFFSET (7) NULL,
    [ClosedDate]                         DATETIMEOFFSET (7) NULL,
    [CreatedByUserID]                    INT             NOT NULL,
    [CreatedDate]                        DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]               INT             NULL,
    [ModifiedDate]                   DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                   INT             NULL,
    [ArchivedDate]                       DATETIMEOFFSET (7) NULL,
    [HRCaseAdvisorUserID]                INT             NULL,
    [AssumedLevelTagTypeID]              INT             NULL,
    [ConfirmedLevelTagTypeID]            INT             NULL,
    [HRCaseOutcomeTypeID]                INT             NULL,
    [IsSuspensionRequired]               BIT             DEFAULT ((0)) NOT NULL,
    [HasLessThan2YearsService]           BIT             DEFAULT ((0)) NOT NULL,
    [IsInProbationaryPeriod]             BIT             DEFAULT ((0)) NOT NULL,
    [IsMedicalReportRequired]            BIT             DEFAULT ((0)) NOT NULL,
    [MedicalReportProviderType]          NVARCHAR (30)   NULL,
    [MedicalReportProviderOccHealthType] NVARCHAR (30)   NULL,
    [HasDisability]                      BIT             NULL,
    [HasAgreedAdjustments]               BIT             NULL,
    [Adjustments]                        NVARCHAR (2000) NULL,
    [AdjustmentsEffectiveFromDate]       DATETIMEOFFSET (7) NULL,
    [HasSkippedInvestigation]            BIT             DEFAULT ((0)) NOT NULL,
    [InvestigatingOfficerEmployeeID]     INT             NULL,
    [InvestigatingOfficerName]           NVARCHAR (100)  NULL,
    [CaseOfficerEmployeeID]              INT             NULL,
    [AppealOfficerEmployeeID]            INT             NULL,
    [TaskScheduleID]                     INT             NULL,
    [LocationID]                         INT             NULL,
    [InvestigationCompletedDate]         DATETIMEOFFSET (7) NULL,
    [DecisionDate]                       DATETIMEOFFSET (7) NULL,
    [AppealDecisionDate]                 DATETIMEOFFSET (7) NULL,
    [NextMeetingDate]                    DATE            NULL,
    [ReferralDate]                       DATETIMEOFFSET (7) NULL,
    [SettlementAgreementValue]           MONEY           NULL,
    [AdvisorEmployeeID]                  INT             NULL,
    [SubmittedByUserTypeID]              INT             DEFAULT ((1)) NULL,
    [RiskLevelID]                        INT             DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([HRCaseID] ASC),
    CONSTRAINT [FK_HRCase_AppealOfficerEmployee] FOREIGN KEY ([AppealOfficerEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_HRCase_ArchivedByUser] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCase_AssumedLevelTagType] FOREIGN KEY ([AssumedLevelTagTypeID]) REFERENCES [V7].[TagType] ([TagTypeID]),
    CONSTRAINT [FK_HRCase_CaseOfficerEmployee] FOREIGN KEY ([CaseOfficerEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_HRCase_ConfirmedLevelTagType] FOREIGN KEY ([ConfirmedLevelTagTypeID]) REFERENCES [V7].[TagType] ([TagTypeID]),
    CONSTRAINT [FK_HRCase_CreatedByUser] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCase_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_HRCase_HRCaseAdvisorUser] FOREIGN KEY ([HRCaseAdvisorUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCase_HRCaseOutcomeType] FOREIGN KEY ([HRCaseOutcomeTypeID]) REFERENCES [V7].[HRCaseOutcomeType] ([HRCaseOutcomeTypeID]),
    CONSTRAINT [FK_HRCase_HRCaseStatusType] FOREIGN KEY ([HRCaseStatusTypeID]) REFERENCES [V7].[HRCaseStatusType] ([HRCaseStatusTypeID]),
    CONSTRAINT [FK_HRCase_HRCategory] FOREIGN KEY ([HRCategoryID]) REFERENCES [V7].[HRCategory] ([HRCategoryID]),
    CONSTRAINT [FK_HRCase_HRType] FOREIGN KEY ([HRTypeID]) REFERENCES [V7].[HRType] ([HRTypeID]),
    CONSTRAINT [FK_HRCase_InvestigatingOfficerEmployee] FOREIGN KEY ([InvestigatingOfficerEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_HRCase_ModifiedByUser] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_HRCase_Location] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_HRCase_SeverityGenericStatusType] FOREIGN KEY ([SeverityGenericStatusTypeID]) REFERENCES [V7].[GenericStatusType] ([GenericStatusTypeID]),
    CONSTRAINT [FK_HRCase_TaskSchedule] FOREIGN KEY ([TaskScheduleID]) REFERENCES [V7].[TaskSchedule] ([TaskScheduleID]),
    CONSTRAINT [FK_HRCase_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

