CREATE TABLE [V7].[IncidentCase] (
    [IncidentCaseID]         INT            IDENTITY (1, 1) NOT NULL,
    [CaseNumber]             NVARCHAR (50)  NOT NULL,
    [AdditionalReference]    NVARCHAR (255) NULL,
    [Description]            NVARCHAR (MAX) NULL,
    [IncidentTypeID]         INT            NOT NULL,
    [UserAreaID]             INT            NOT NULL,
    [IncidentDate]           DATETIMEOFFSET (7) NOT NULL,
    [ReportedDate]           DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NULL,
    [LocationID]             INT            NULL,
    [IncidentSeverityTypeID] INT            DEFAULT (1) NULL,
    [IncidentStatusTypeID]   INT            DEFAULT (1) NULL,
    [IncidentPriorityTypeID] INT            DEFAULT (2) NULL,
    [ReportedByUserID]       INT            NOT NULL,
    [AssignedToUserID]       INT            NULL,
    [InvolvedEmployeeID]     INT            NULL,
    [InvestigationStartDate] DATETIMEOFFSET (7) NULL,
    [InvestigationEndDate]   DATETIMEOFFSET (7) NULL,
    [RootCause]              NVARCHAR (MAX) NULL,
    [CorrectiveActions]      NVARCHAR (MAX) NULL,
    [PreventiveActions]      NVARCHAR (MAX) NULL,
    [ClosedDate]             DATETIMEOFFSET (7) NULL,
    [ClosedByUserID]         INT            NULL,
    [ClosureNotes]           NVARCHAR (MAX) NULL,
    [IsDeleted]              BIT            DEFAULT ((0)) NULL,
    [CreatedDate]            DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NULL,
    [CreatedByUserID]        INT            NOT NULL,
    [ModifiedDate]           DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NULL,
    [ModifiedByUserID]       INT            NOT NULL,
    [ArchivedDate]           DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]       INT            NULL,
    PRIMARY KEY CLUSTERED ([IncidentCaseID] ASC),
    FOREIGN KEY ([IncidentTypeID]) REFERENCES [V7].[IncidentType] ([IncidentTypeID]),
    FOREIGN KEY ([IncidentSeverityTypeID]) REFERENCES [V7].[IncidentSeverityType] ([IncidentSeverityTypeID]),
    FOREIGN KEY ([IncidentStatusTypeID]) REFERENCES [V7].[IncidentStatusType] ([IncidentStatusTypeID]),
    FOREIGN KEY ([IncidentPriorityTypeID]) REFERENCES [V7].[IncidentPriorityType] ([IncidentPriorityTypeID]),
    UNIQUE NONCLUSTERED ([CaseNumber] ASC)
);

