CREATE TABLE [V7].[IncidentCategoryType] (
    [IncidentCategoryTypeID] INT           IDENTITY (1, 1) NOT NULL,
    [UserAreaID]             INT           NULL,
    [Title]                  NVARCHAR (100) NOT NULL,
    [Reference]              NVARCHAR (50) NOT NULL,
    [Description]            NVARCHAR (500) NULL,
    [ColorCode]              NVARCHAR (50) NULL,
    [Icon]                   NVARCHAR (50) NULL,
    [DisplayOrder]           INT           NULL,
    [IsActive]               BIT           DEFAULT ((1)) NULL,
    [CreatedByUserID]        INT           NOT NULL,
    [CreatedDate]            DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NOT NULL,
    [ModifiedByUserID]       INT           NULL,
    [ModifiedDate]           DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]       INT           NULL,
    [ArchivedDate]           DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([IncidentCategoryTypeID] ASC),
    UNIQUE NONCLUSTERED ([Reference] ASC),
    CONSTRAINT [FK_IncidentCategoryType_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_IncidentCategoryType_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_IncidentCategoryType_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_IncidentCategoryType_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);
