CREATE TABLE [V7].[IncidentStatusType] (
    [IncidentStatusTypeID]     INT           IDENTITY (1, 1) NOT NULL,
    [UserAreaID]               INT           NULL,
    [Reference]                NVARCHAR (20) NOT NULL,
    [Title]                    NVARCHAR (50) NOT NULL,
    [StatusOrder]              INT           NOT NULL,
    [ColorCode]                NVARCHAR (50) NULL,
    [Description]              NVARCHAR (255) NULL,
    [IsActive]                 BIT           DEFAULT ((1)) NULL,
    [CreatedByUserID]          INT           NOT NULL,
    [CreatedDate]              DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]         INT           NULL,
    [ModifiedDate]             DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]         INT           NULL,
    [ArchivedDate]             DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([IncidentStatusTypeID] ASC),
    UNIQUE NONCLUSTERED ([Reference] ASC),
    CONSTRAINT [FK_IncidentStatusType_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [FK_IncidentStatusType_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_IncidentStatusType_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_IncidentStatusType_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID])
);
