CREATE TABLE [V7].[MethodStatementStep] (
    [MethodStatementStepID]       INT                IDENTITY (1, 1) NOT NULL,
    [UserAreaID]                  INT                NOT NULL,
    [MethodStatementID]           INT                NOT NULL,
    [StepNumber]                  INT                NOT NULL,
    [StepTitle]                   NVARCHAR (255)     NOT NULL,
    [StepDescription]             NVARCHAR (MAX)     NOT NULL,
    [StepDuration]                INT                NULL,
    [PersonnelRequired]           INT                DEFAULT ((1)) NULL,
    [SpecificRoles]               NVARCHAR (500)     NULL,
    [KeyHazards]                  NVARCHAR (MAX)     NULL,
    [SafetyPrecautions]           NVARCHAR (MAX)     NULL,
    [RequiredPPE]                 NVARCHAR (500)     NULL,
    [RequiredEquipment]           NVARCHAR (MAX)     NULL,
    [ToolsRequired]               NVARCHAR (MAX)     NULL,
    [InspectionPoints]            NVARCHAR (MAX)     NULL,
    [QualityChecks]               NVARCHAR (MAX)     NULL,
    [AcceptanceCriteria]          NVARCHAR (MAX)     NULL,
    [CriticalControlPoints]       NVARCHAR (MAX)     NULL,
    [EnvironmentalConsiderations] NVARCHAR (MAX)     NULL,
    [Notes]                       NVARCHAR (MAX)     NULL,
    [CreatedByUserID]             INT                NOT NULL,
    [CreatedDate]                 DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NOT NULL,
    [ModifiedByUserID]        INT                NULL,
    [ModifiedDate]            DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]            INT                NULL,
    [ArchivedDate]                DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_MethodStatementStep] PRIMARY KEY CLUSTERED ([MethodStatementStepID] ASC)
);

