CREATE TABLE [V7].[MethodStatement] (
    [MethodStatementID]    INT                IDENTITY (1, 1) NOT NULL,
    [UserAreaID]           INT                NOT NULL,
    [SSOWDocumentTypeID]   INT                NOT NULL,
    [SSOWStatusTypeID]     INT                NOT NULL,
    [DocumentNumber]       NVARCHAR (50)      NOT NULL,
    [DocumentTitle]        NVARCHAR (255)     NOT NULL,
    [DocumentVersion]      NVARCHAR (20)      DEFAULT ('1.0') NULL,
    [PreviousVersionID]    INT                NULL,
    [IsCurrentVersion]     BIT                DEFAULT ((1)) NULL,
    [WorkDescription]      NVARCHAR (MAX)     NOT NULL,
    [Location]             NVARCHAR (500)     NULL,
    [Equipment]            NVARCHAR (MAX)     NULL,
    [Materials]            NVARCHAR (MAX)     NULL,
    [MinimumPersonnel]     INT                DEFAULT ((1)) NULL,
    [MaximumPersonnel]     INT                NULL,
    [RequiredCompetencies] NVARCHAR (MAX)     NULL,
    [TrainingRequirements] NVARCHAR (MAX)     NULL,
    [SSOWRiskCategoryID]   INT                NULL,
    [MainHazards]          NVARCHAR (MAX)     NULL,
    [RiskAssessmentID]     INT                NULL,
    [AuthorUserID]         INT                NOT NULL,
    [ReviewerUserID]       INT                NULL,
    [ApproverUserID]       INT                NULL,
    [ReviewDate]           DATETIMEOFFSET (7) NULL,
    [ApprovalDate]         DATETIMEOFFSET (7) NULL,
    [NextReviewDate]       DATETIMEOFFSET (7) NULL,
    [PublishedDate]        DATETIMEOFFSET (7) NULL,
    [PublishedByUserID]    INT                NULL,
    [EffectiveDate]        DATETIMEOFFSET (7) NULL,
    [ExpiryDate]           DATETIMEOFFSET (7) NULL,
    [EmergencyProcedures]  NVARCHAR (MAX)     NULL,
    [EmergencyContacts]    NVARCHAR (MAX)     NULL,
    [LegalRequirements]    NVARCHAR (MAX)     NULL,
    [References]           NVARCHAR (MAX)     NULL,
    [AdditionalNotes]      NVARCHAR (MAX)     NULL,
    [IsActive]             BIT                DEFAULT ((1)) NULL,
    [CreatedByUserID]      INT                NOT NULL,
    [CreatedDate]          DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NOT NULL,
    [ModifiedByUserID] INT                NULL,
    [ModifiedDate]     DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]     INT                NULL,
    [ArchivedDate]         DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_MethodStatement] PRIMARY KEY CLUSTERED ([MethodStatementID] ASC)
);

