CREATE TABLE [V7].[MigrateV5TempChecklistQuestionnaireResponse] (
    [ROWID]                      INT             IDENTITY (1, 1) NOT NULL,
    [intTCRParentId]             INT             NULL,
    [UserID]                     INT             NOT NULL,
    [UserAreaID]                 INT             NOT NULL,
    [CreatedDate]                DATETIMEOFFSET (7) NOT NULL,
    [Totalscore]                 TINYINT         NULL,
    [ChecklistId]                INT             NOT NULL,
    [ChecklistVersion]           DECIMAL (4, 1)  NOT NULL,
    [ChecklistTemplateID]        INT             NULL,
    [IncidentID]                 INT             NULL,
    [DepartmentID]               INT             NULL,
    [EmployeeID]                 INT             NULL,
    [UserInputDate]              DATETIMEOFFSET (7) NULL,
    [Modified]                   DATETIMEOFFSET (7) NULL,
    [Latest]                     BIT             NOT NULL,
    [xmlTCRresponse]             XML             NOT NULL,
    [AccidentPersonTitle]        NVARCHAR (1000) NULL,
    [V5Reference]                VARCHAR (255)   NULL,
    [V5AdditionalReference]      VARCHAR (255)   NULL,
    [DateOfIncident]             DATETIMEOFFSET (7) NULL,
    [DateLogged]                 DATETIMEOFFSET (7) NULL,
    [CompletedByTitle]           VARCHAR (250)   NULL,
    [LocationTitle]              VARCHAR (350)   NULL,
    [V6QuestionnnaireResponseID] INT             NULL,
    [V6AccidentCaseID]           INT             NULL,
    [V6AccidentPersonID]         INT             NULL
);

