CREATE TABLE [V7].[Process] (
    [ProcessID]            INT                IDENTITY (1, 1) NOT NULL,
    [UserAreaID]           INT                NOT NULL,
    [ProcessName]          NVARCHAR (255)     NOT NULL,
    [ProcessType]          NVARCHAR (50)      NOT NULL,
    [Description]          NVARCHAR (MAX)     NULL,
    [ChainDefinition]      NVARCHAR (MAX)     NULL,
    [Version]              INT                DEFAULT ((1)) NULL,
    [Status]               NVARCHAR (50)      DEFAULT ('Active') NULL,
    [Priority]             NVARCHAR (20)      DEFAULT ('Medium') NULL,
    [EstimatedDuration]    INT                NULL,
    [MaxRetries]           INT                DEFAULT ((3)) NULL,
    [TimeoutMinutes]       INT                DEFAULT ((60)) NULL,
    [IsTemplate]           BIT                DEFAULT ((0)) NULL,
    [TemplateCategory]     NVARCHAR (100)     NULL,
    [CategoryTypeID]       INT                NULL,
    [CreatedByUserID]      INT                NOT NULL,
    [CreatedDate]          DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NOT NULL,
    [ModifiedByUserID] INT                NULL,
    [ModifiedDate]     DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]     INT                NULL,
    [ArchivedDate]         DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK_Process] PRIMARY KEY CLUSTERED ([ProcessID] ASC),
    CONSTRAINT [CK_Process_Priority] CHECK ([Priority]='Critical' OR [Priority]='High' OR [Priority]='Medium' OR [Priority]='Low'),
    CONSTRAINT [CK_Process_ProcessType] CHECK ([ProcessType]='manual' OR [ProcessType]='automated' OR [ProcessType]='approval' OR [ProcessType]='workflow'),
    CONSTRAINT [CK_Process_Status] CHECK ([Status]='Archived' OR [Status]='Draft' OR [Status]='Inactive' OR [Status]='Active'),
    CONSTRAINT [FK_Process_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Process_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Process_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Process_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

