CREATE TABLE [V7].[RecruitmentVacancy] (
    [RecruitmentVacancyID] INT            IDENTITY (1, 1) NOT NULL,
    [UserAreaID]           INT            NOT NULL,
    [Reference]            NVARCHAR (20)  NOT NULL,
    [JobTitle]             NVARCHAR (255) NOT NULL,
    [ManagerDetails]       NVARCHAR (255) NULL,
    [DepartmentDetails]    NVARCHAR (255) NULL,
    [OtherDetails]         NVARCHAR (MAX) NULL,
    [SuggestedStartDate]   DATETIMEOFFSET (7) NULL,
    [VacancyOpeningDate]   DATETIMEOFFSET (7) NULL,
    [VacancyClosingDate]   DATETIMEOFFSET (7) NULL,
    [TotalVacancies]       TINYINT        DEFAULT ((1)) NOT NULL,
    [CreatedByUserID]      INT            NOT NULL,
    [CreatedDate]          DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID] INT            NULL,
    [ModifiedDate]     DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]     INT            NULL,
    [ArchivedDate]         DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([RecruitmentVacancyID] ASC),
    CONSTRAINT [FK_RecruitmentVacancy_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_RecruitmentVacancy_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_RecruitmentVacancy_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_RecruitmentVacancy_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

