CREATE TABLE [V7].[SafeSystemOfWork] (
    [SafeSystemOfWorkID]           INT            IDENTITY (1, 1) NOT NULL,
    [SafeSystemOfWorkTypeID]       INT            NOT NULL,
    [SafeSystemOfWorkTemplateID]   INT            NOT NULL,
    [ApprovalStatusTypeID]         INT            NOT NULL,
    [OrgGroupID]                   INT            NULL,
    [LocationID]                   INT            NULL,
    [UserAreaID]                   INT            NOT NULL,
    [TextBlockCollectionID]        INT            NULL,
    [OriginalSafeSystemOfWorkID]   INT            NULL,
    [Version]                      INT            CONSTRAINT [DF__SafeSyste__Versi__68E867AC] DEFAULT ((1)) NOT NULL,
    [Title] NVARCHAR (255) NULL,
    [Description] NVARCHAR (MAX) NULL,
    [LocationDetails] NVARCHAR (MAX) NULL,
    [DurationDetails] NVARCHAR (MAX) NULL,
    [RelatedRecordDetails] NVARCHAR (MAX) NULL,
    [WorkStartDate]                DATETIMEOFFSET (7) NULL,
    [WorkEndDate]                  DATETIMEOFFSET (7) NULL,
    [ValidFromDate]                DATETIMEOFFSET (7) NULL,
    [ValidToDate]                  DATETIMEOFFSET (7) NULL,
    [IssueDate]                    DATETIMEOFFSET (7) NULL,
    [CompletedDate]                DATETIMEOFFSET (7) NULL,
    [CreatedByUserID]              INT            NOT NULL,
    [CreatedDate]                  DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]         INT            NULL,
    [ModifiedDate]             DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]             INT            NULL,
    [ArchivedDate]                 DATETIMEOFFSET (7) NULL,
    [Signature]                    NVARCHAR (MAX) NULL,
    [IsEnvironmental]              BIT            DEFAULT ((0)) NOT NULL,
    [IncludePPEOptions]            BIT            DEFAULT ((1)) NOT NULL,
    [IncludeRiskAssessmentOptions] BIT            DEFAULT ((1)) NOT NULL,
    [IncludeSSOWLinks]             BIT            DEFAULT ((1)) NOT NULL,
    [IncludeAdvancedDetails]       BIT            DEFAULT ((1)) NOT NULL,
    [IsUploadedPermit]             BIT            DEFAULT ((0)) NOT NULL,
    [PermitAttachmentID]           INT            NULL,
    [ContractorCompanyID]          INT            NULL,
    [ReviewDate]                   DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK__SafeSyst__1ED1B1908F3FC9A0] PRIMARY KEY CLUSTERED ([SafeSystemOfWorkID] ASC),
    CONSTRAINT [FK_SafeSystemOfWork_ApprovalStatusTypeID] FOREIGN KEY ([ApprovalStatusTypeID]) REFERENCES [V7].[ApprovalStatusType] ([ApprovalStatusTypeID]),
    CONSTRAINT [FK_SafeSystemOfWork_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_SafeSystemOfWork_ContractorCompanyID] FOREIGN KEY ([ContractorCompanyID]) REFERENCES [V7].[ContractorCompany] ([ContractorCompanyID]),
    CONSTRAINT [FK_SafeSystemOfWork_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_SafeSystemOfWork_LocationID] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_SafeSystemOfWork_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_SafeSystemOfWork_OrgGroupID] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_SafeSystemOfWork_OriginalSafeSystemOfWorkID] FOREIGN KEY ([OriginalSafeSystemOfWorkID]) REFERENCES [V7].[SafeSystemOfWork] ([SafeSystemOfWorkID]),
    CONSTRAINT [FK_SafeSystemOfWork_PermitAttachmentID] FOREIGN KEY ([PermitAttachmentID]) REFERENCES [V7].[Attachment] ([AttachmentID]),
    CONSTRAINT [FK_SafeSystemOfWork_SafeSystemOfWorkTemplateID] FOREIGN KEY ([SafeSystemOfWorkTemplateID]) REFERENCES [V7].[SafeSystemOfWorkTemplate] ([SafeSystemOfWorkTemplateID]),
    CONSTRAINT [FK_SafeSystemOfWork_SafeSystemOfWorkTypeID] FOREIGN KEY ([SafeSystemOfWorkTypeID]) REFERENCES [V7].[SafeSystemOfWorkType] ([SafeSystemOfWorkTypeID]),
    CONSTRAINT [FK_SafeSystemOfWork_TextBlockCollectionID] FOREIGN KEY ([TextBlockCollectionID]) REFERENCES [V7].[TextBlockCollection] ([TextBlockCollectionID]),
    CONSTRAINT [FK_SafeSystemOfWork_UserAreaID] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

