CREATE TABLE [V7].[TaskSchedule] (
    [TaskScheduleID]              INT                IDENTITY (1, 1) NOT NULL,
    [UserAreaID]                  INT                NOT NULL,
    [TaskTypeID]                  INT                NOT NULL,
    [Reference]                   NVARCHAR (50)      NULL,
    [Title]                       NVARCHAR (1000)    NOT NULL,
    [Description]                 NVARCHAR (MAX)     NULL,
    [StartDate]                   DATE               NOT NULL,
    [NextProcessingDate]          DATE               NULL,
    [FrequencyTypeID]             INT                NOT NULL,
    [FrequencyPeriod]             INT                NULL,
    [TaskDueAlertPeriodOverride]  TINYINT            DEFAULT ((0)) NOT NULL,
    [IsOneTaskCreatedForMultiple] BIT                DEFAULT ((1)) NOT NULL,
    [IsNextProcessingDone]        BIT                DEFAULT ((0)) NOT NULL,
    [CreatedByUserID]             INT                NOT NULL,
    [CreatedDate]                 DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]        INT                NULL,
    [ModifiedDate]            DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]            INT                NULL,
    [ArchivedDate]                DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([TaskScheduleID] ASC),
    CONSTRAINT [FK_TaskSchedule_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TaskSchedule_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TaskSchedule_FrequencyType] FOREIGN KEY ([FrequencyTypeID]) REFERENCES [V7].[FrequencyType] ([FrequencyTypeID]),
    CONSTRAINT [FK_TaskSchedule_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TaskSchedule_TaskType] FOREIGN KEY ([TaskTypeID]) REFERENCES [V7].[TaskType] ([TaskTypeID]),
    CONSTRAINT [FK_TaskSchedule_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

