CREATE TABLE [V7].[TextBlockCollection] (
    [TextBlockCollectionID]         INT           IDENTITY (1, 1) NOT NULL,
    [TextBlockTypeID]               INT           NOT NULL,
    [TextBlockStatusTypeID]         INT           NOT NULL,
    [TextBlockCategoryID]           INT           NULL,
    [OriginalTextBlockCollectionID] INT           NULL,
    [OrgGroupID]                    INT           NULL,
    [UserAreaID]                    INT           NOT NULL,
    [IsEnvironmental]               BIT           CONSTRAINT [DF__TextBlock__IsEnv__04515656] DEFAULT ((0)) NOT NULL,
    [Title] NVARCHAR (255) NULL,
    [Keywords] NVARCHAR (255) NULL,
    [CreatedByUserID]               INT           NOT NULL,
    [CreatedDate]                   DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]          INT           NULL,
    [ModifiedDate]              DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]              INT           NULL,
    [ArchivedDate]                  DATETIMEOFFSET (7) NULL,
    [Version]                       TINYINT       DEFAULT ((1)) NOT NULL,
    [OrderNum]                      INT           DEFAULT ((1)) NOT NULL,
    [LocationID]                    INT           NULL,
    [Reference]                     NVARCHAR (50) NULL,
    [UseCalculatedVersion]          BIT           DEFAULT ((0)) NOT NULL,
    [TemplateTextBlockCollectionID] INT           NULL,
    CONSTRAINT [PK__TextBloc__A3A341D78BE3ADB7] PRIMARY KEY CLUSTERED ([TextBlockCollectionID] ASC),
    CONSTRAINT [FK_TextBlockCollection_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TextBlockCollection_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TextBlockCollection_Location] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_TextBlockCollection_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TextBlockCollection_OrgGroup] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_TextBlockCollection_OriginalTextBlockCollection] FOREIGN KEY ([OriginalTextBlockCollectionID]) REFERENCES [V7].[TextBlockCollection] ([TextBlockCollectionID]),
    CONSTRAINT [FK_TextBlockCollection_TemplateTextBlockCollection] FOREIGN KEY ([TemplateTextBlockCollectionID]) REFERENCES [V7].[TextBlockCollection] ([TextBlockCollectionID]),
    CONSTRAINT [FK_TextBlockCollection_TextBlockCategory] FOREIGN KEY ([TextBlockCategoryID]) REFERENCES [V7].[TextBlockCategory] ([TextBlockCategoryID]),
    CONSTRAINT [FK_TextBlockCollection_TextBlockStatusType] FOREIGN KEY ([TextBlockStatusTypeID]) REFERENCES [V7].[TextBlockStatusType] ([TextBlockStatusTypeID]),
    CONSTRAINT [FK_TextBlockCollection_TextBlockType] FOREIGN KEY ([TextBlockTypeID]) REFERENCES [V7].[TextBlockType] ([TextBlockTypeID]),
    CONSTRAINT [FK_TextBlockCollection_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

