CREATE TABLE [V7].[TextBlock] (
    [TextBlockID]            INT              IDENTITY (1, 1) NOT NULL,
    [TextBlockTypeID]        INT              NOT NULL,
    [TextBlockStatusTypeID]  INT              NOT NULL,
    [TextBlockCollectionID]  INT              NULL,
    [TextBlockCategoryID]    INT              NULL,
    [TextBlockSectionID]     INT              NULL,
    [OriginalTextBlockID]    INT              NULL,
    [TemplateTextBlockID]    INT              NULL,
    [UserAreaID]             INT              NULL,
    [OrgGroupID]             INT              NULL,
    [Reference]              NVARCHAR (40)    NULL,
    [OrderNum]               INT              CONSTRAINT [DF__TextBlock__Order__1DBB5747] DEFAULT ((0)) NOT NULL,
    [Title] NVARCHAR (255) NULL,
    [Content] NVARCHAR (MAX) NULL,
    [RelatedURL] NVARCHAR (255) NULL,
    [Keywords] NVARCHAR (255) NULL,
    [IsMultiLine]            BIT              CONSTRAINT [DF__TextBlock__IsMul__15BB0E23] DEFAULT ((1)) NOT NULL,
    [IsFixedTitle]           BIT              CONSTRAINT [DF__TextBlock__IsFix__16AF325C] DEFAULT ((0)) NOT NULL,
    [CanUploadAttachments]   BIT              CONSTRAINT [DF_TextBlock_CanUploadAttachments] DEFAULT ((1)) NOT NULL,
    [YesNoNATypeID]          INT              NULL,
    [YesNoNAValue]           BIT              NULL,
    [IsEnvironmental]        BIT              CONSTRAINT [DF__TextBlock__IsEnv__035D321D] DEFAULT ((0)) NOT NULL,
    [CreatedByUserID]        INT              NOT NULL,
    [CreatedDate]            DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]   INT              NULL,
    [ModifiedDate]       DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]       INT              NULL,
    [ArchivedDate]           DATETIMEOFFSET (7) NULL,
    [ThemeID]                INT              NULL,
    [Version]                TINYINT          DEFAULT ((1)) NOT NULL,
    [OrderType]              INT              DEFAULT ((0)) NOT NULL,
    [tempid]                 INT              NULL,
    [CopiedFromTemplateDate] DATETIMEOFFSET (7) NULL,
    [SharedID]               UNIQUEIDENTIFIER NULL,
    [IsDSE]                  BIT              DEFAULT ((0)) NOT NULL,
    [ExposureTypeID]         INT              NULL,
    [YesNoNAEnum]            TINYINT          NULL,
    CONSTRAINT [PK__TextBloc__08827E8EEECEAE63] PRIMARY KEY CLUSTERED ([TextBlockID] ASC),
    CONSTRAINT [FK_TextBlock_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TextBlock_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TextBlock_ExposureType] FOREIGN KEY ([ExposureTypeID]) REFERENCES [V7].[ExposureType] ([ExposureTypeID]),
    CONSTRAINT [FK_TextBlock_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_TextBlock_OrgGroup] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_TextBlock_OriginalTextBlock] FOREIGN KEY ([OriginalTextBlockID]) REFERENCES [V7].[TextBlock] ([TextBlockID]),
    CONSTRAINT [FK_TextBlock_TemplateTextBlock] FOREIGN KEY ([TemplateTextBlockID]) REFERENCES [V7].[TextBlock] ([TextBlockID]),
    CONSTRAINT [FK_TextBlock_TextBlockCategory] FOREIGN KEY ([TextBlockCategoryID]) REFERENCES [V7].[TextBlockCategory] ([TextBlockCategoryID]),
    CONSTRAINT [FK_TextBlock_TextBlockCollection] FOREIGN KEY ([TextBlockCollectionID]) REFERENCES [V7].[TextBlockCollection] ([TextBlockCollectionID]),
    CONSTRAINT [FK_TextBlock_TextBlockSection] FOREIGN KEY ([TextBlockSectionID]) REFERENCES [V7].[TextBlockSection] ([TextBlockSectionID]),
    CONSTRAINT [FK_TextBlock_TextBlockStatusType] FOREIGN KEY ([TextBlockStatusTypeID]) REFERENCES [V7].[TextBlockStatusType] ([TextBlockStatusTypeID]),
    CONSTRAINT [FK_TextBlock_TextBlockType] FOREIGN KEY ([TextBlockTypeID]) REFERENCES [V7].[TextBlockType] ([TextBlockTypeID]),
    CONSTRAINT [FK_TextBlock_ThemeID] FOREIGN KEY ([ThemeID]) REFERENCES [V7].[Theme] ([ThemeID]),
    CONSTRAINT [FK_TextBlock_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [FK_TextBlock_YesNoNAType] FOREIGN KEY ([YesNoNATypeID]) REFERENCES [V7].[YesNoNAType] ([YesNoNATypeID])
);


GO
CREATE NONCLUSTERED INDEX [IX_TextBlock_TextBlockTypeID_UserAreaID_ThemeID_includes]
    ON [V7].[TextBlock]([TextBlockTypeID] ASC, [UserAreaID] ASC, [ThemeID] ASC)
    INCLUDE([TextBlockID], [TextBlockStatusTypeID], [TextBlockCollectionID], [TextBlockCategoryID], [TextBlockSectionID], [OriginalTextBlockID], [TemplateTextBlockID], [OrgGroupID], [Reference], [OrderNum], [IsMultiLine], [IsFixedTitle], [CanUploadAttachments], [YesNoNATypeID], [YesNoNAValue], [CreatedByUserID], [CreatedDate], [ModifiedByUserID], [ModifiedDate], [ArchivedDate]);

