CREATE TABLE [V7].[UserAreaFormQuestion] (
    [UserAreaFormQuestionID]         INT                IDENTITY (1, 1) NOT NULL,
    [OriginalUserAreaFormQuestionID] INT                NULL,
    [UserAreaFormSectionID]          INT                NOT NULL,
    [AnswerTypeID]                   INT                NOT NULL,
    [Title]                          NVARCHAR (255)     NOT NULL,
    [Description]                    NVARCHAR (MAX)     NULL,
    [ConfigData]                     NVARCHAR (MAX)     NULL,
    [ParentIDAnswerValues]           NVARCHAR (MAX)     NULL,
    [AnswerTypeOptionsTable]         NVARCHAR (50)      NULL,
    [AnswerTypeOptionsList]          NVARCHAR (MAX)     NULL,
    [OrderNum]                       TINYINT            DEFAULT ((0)) NOT NULL,
    [Weighting]                      TINYINT            NULL,
    [MaxScore]                       TINYINT            NULL,
    [IsMandatory]                    BIT                DEFAULT ((0)) NOT NULL,
    [CreatedByUserID]                INT                NOT NULL,
    [CreatedDate]                    DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]           INT                NULL,
    [ModifiedDate]               DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]               INT                NULL,
    [ArchivedDate]                   DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([UserAreaFormQuestionID] ASC),
    CONSTRAINT [FK_UserAreaFormQuestion_AnswerType] FOREIGN KEY ([AnswerTypeID]) REFERENCES [V7].[AnswerType] ([AnswerTypeID]),
    CONSTRAINT [FK_UserAreaFormQuestion_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaFormQuestion_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaFormQuestion_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaFormQuestion_UserAreaFormSection] FOREIGN KEY ([UserAreaFormSectionID]) REFERENCES [V7].[UserAreaFormSection] ([UserAreaFormSectionID])
);

