CREATE TABLE [V7].[UserAreaMonitoringReport] (
    [UserAreaMonitoringReportID]        INT      IDENTITY (1, 1) NOT NULL,
    [UserAreaID]                        INT      NOT NULL,
    [XMLReport]                         XML      NOT NULL,
    [StartDate]                         DATETIMEOFFSET (7) NOT NULL,
    [EndDate]                           DATETIMEOFFSET (7) NOT NULL,
    [UserAreaMonitoringReportTypeID]    INT      NOT NULL,
    [IsV5GeneratedReport]               BIT      CONSTRAINT [DF__UserAreaM__IsV5G__509CA826] DEFAULT ((0)) NULL,
    [HasBeenProcessedByService]         BIT      CONSTRAINT [DF__UserAreaM__HasBe__5190CC5F] DEFAULT ((0)) NOT NULL,
    [MonitoringReportXsltTransformerID] INT      NOT NULL,
    [LanguageTypeID]                    INT      NOT NULL,
    [RegionTypeID]                      INT      NOT NULL,
    [CreatedByUserID]                   INT      NOT NULL,
    [CreatedDate]                       DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]              INT      NULL,
    [ModifiedDate]                  DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                  INT      NULL,
    [ArchivedDate]                      DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK__UserArea__66C68879BB99C517] PRIMARY KEY CLUSTERED ([UserAreaMonitoringReportID] ASC),
    CONSTRAINT [FK_UserAreaMonitoringReport_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_LanguageType] FOREIGN KEY ([LanguageTypeID]) REFERENCES [V7].[LanguageType] ([LanguageTypeID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_MonitoringReportXsltTransformer] FOREIGN KEY ([MonitoringReportXsltTransformerID]) REFERENCES [V7].[MonitoringReportXsltTransformer] ([MonitoringReportXsltTransformerID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_RegionType] FOREIGN KEY ([RegionTypeID]) REFERENCES [V7].[RegionType] ([RegionTypeID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [FK_UserAreaMonitoringReport_UserAreaMonitoringReportType] FOREIGN KEY ([UserAreaMonitoringReportTypeID]) REFERENCES [V7].[UserAreaMonitoringReportType] ([UserAreaMonitoringReportTypeID])
);

