CREATE TABLE [V7].[UserAreaRiskAssessmentSettings] (
    [UserAreaRiskAssessmentSettingsID]         INT            IDENTITY (1, 1) NOT NULL,
    [DefaultRiskMatrixTypeID]                  INT            NULL,
    [DefaultComplianceScoreTypeID]             INT            NULL,
    [UserAreaID]                               INT            NOT NULL,
    [IsPreAndPostControlRiskLevelUsed]         BIT            CONSTRAINT [DF__UserAreaR__IsPre__0AF29B96] DEFAULT ((0)) NOT NULL,
    [ExcludeGlobalRAsFromOrgGroupEmployees]    BIT            CONSTRAINT [DF__UserAreaR__Exclu__7252A1AC] DEFAULT ((0)) NOT NULL,
    [IncludeAllRAForSSOW]                      BIT            CONSTRAINT [DF_UserAreaRiskAssessmentSettings_IncludeAllRAForSSOW] DEFAULT ((0)) NOT NULL,
    [EnableBasicMode]                          BIT            CONSTRAINT [DF__UserAreaR__Enabl__2CDE6A9D] DEFAULT ((0)) NOT NULL,
    [EnableDynamicRA]                          BIT            CONSTRAINT [DF__UserAreaR__Enabl__1F5A524D] DEFAULT ((0)) NOT NULL,
    [RiskMatrixTypeIDs]                        VARCHAR (20)   NULL,
    [AllowHazardsWithoutRiskLevels]            BIT            DEFAULT ((0)) NOT NULL,
    [AllowHazardsWithoutControlMeasures]       BIT            DEFAULT ((0)) NOT NULL,
    [EnableSingleHazardView]                   BIT            DEFAULT ((0)) NOT NULL,
    [CreatedByUserID]                          INT            NULL,
    [CreatedDate]                              DATETIMEOFFSET (7) NULL,
    [ModifiedByUserID]                     INT            NULL,
    [ModifiedDate]                         DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                         INT            NULL,
    [ArchivedDate]                             DATETIMEOFFSET (7) NULL,
    [DisableNoMonitoringRequired]              BIT            DEFAULT ((0)) NOT NULL,
    [DisableNoReviewRequired]                  BIT            DEFAULT ((0)) NOT NULL,
    [IsPreAndPostControlRiskLevelConfigurable] BIT            DEFAULT ((0)) NOT NULL,
    [EnforceFAsForNonCompliantControlMeasures] BIT            DEFAULT ((0)) NOT NULL,
    [ReviewDefaultFrequencyPeriod]            INT            NULL,
    [ReviewDefaultFrequencyTypeID]            INT            NULL,
    [MonitorDefaultFrequencyPeriod]            INT            NULL,
    [MonitorDefaultFrequencyTypeID]            INT            NULL,
    [MonitoringScoreOptionValues]              NVARCHAR (100) NULL,
    CONSTRAINT [PK__UserArea__785A011F995A734A] PRIMARY KEY CLUSTERED ([UserAreaRiskAssessmentSettingsID] ASC),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_ComplianceScoreType] FOREIGN KEY ([DefaultComplianceScoreTypeID]) REFERENCES [V7].[ComplianceScoreType] ([ComplianceScoreTypeID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_MonitorDefaultFrequencyType] FOREIGN KEY ([MonitorDefaultFrequencyTypeID]) REFERENCES [V7].[FrequencyType] ([FrequencyTypeID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_ReviewDefaultFrequencyType] FOREIGN KEY ([ReviewDefaultFrequencyTypeID]) REFERENCES [V7].[FrequencyType] ([FrequencyTypeID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_RiskMatrixType] FOREIGN KEY ([DefaultRiskMatrixTypeID]) REFERENCES [V7].[RiskMatrixType] ([RiskMatrixTypeID]),
    CONSTRAINT [FK_UserAreaRiskAssessmentSettings_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [CK_UserAreaRiskAssessmentSettings_UserArea] UNIQUE NONCLUSTERED ([UserAreaID] ASC)
);

