CREATE TABLE [V7].[UserAreaFormResponse] (
    [UserAreaFormResponseID]         INT                IDENTITY (1, 1) NOT NULL,
    [OriginalUserAreaFormResponseID] INT                NULL,
    [Version]                        TINYINT            NOT NULL,
    [Status]                         NVARCHAR (20)      NOT NULL,
    [UserAreaFormID]                 INT                NOT NULL,
    [UserAreaID]                     INT                NOT NULL,
    [EmployeeID]                     INT                NOT NULL,
    [LocationID]                     INT                NULL,
    [OrgGroupID]                     INT                NULL,
    [Reference]                      NVARCHAR (100)     NULL,
    [QuestionResponseData]           NVARCHAR (MAX)     NULL,
    [AttachmentIDList]               NVARCHAR (1000)    NULL,
    [TaskIDList]                     NVARCHAR (1000)    NULL,
    [SubmissionDate]                 DATETIMEOFFSET (7) NULL,
    [CreatedByUserID]                INT                NOT NULL,
    [CreatedDate]                    DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]           INT                NULL,
    [ModifiedDate]               DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]               INT                NULL,
    [ArchivedDate]                   DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([UserAreaFormResponseID] ASC),
    CONSTRAINT [FK_UserAreaFormResponse_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaFormResponse_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaFormResponse_Employee] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_UserAreaFormResponse_Location] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_UserAreaFormResponse_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_UserAreaFormResponse_OrgGroup] FOREIGN KEY ([OrgGroupID]) REFERENCES [V7].[OrgGroup] ([OrgGroupID]),
    CONSTRAINT [FK_UserAreaFormResponse_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [FK_UserAreaFormResponse_UserAreaForm] FOREIGN KEY ([UserAreaFormID]) REFERENCES [V7].[UserAreaForm] ([UserAreaFormID])
);

