CREATE TABLE [V7].[WalkAssignment] (
    [WalkAssignmentID]                INT            IDENTITY (1, 1) NOT NULL,
    [WalkID]                          INT            NOT NULL,
    [EmployeeID]                      INT            NOT NULL,
    [TaskScheduleID]                  INT            NULL,
    [TaskID]                          INT            NULL,
    [IsSignatureRequired]             BIT            DEFAULT ((0)) NOT NULL,
    [ManagerSignatureID]              INT            NULL,
    [SignatureText]                   NVARCHAR (MAX) NULL,
    [CompletedByFullName]             NVARCHAR (100) NULL,
    [DueDate]                         DATETIMEOFFSET (7) NOT NULL,
    [PreStartDuration]                INT            NULL,
    [PostStartDuration]               INT            NULL,
    [MinStartDate]                    DATETIMEOFFSET (7) NULL,
    [MaxStartDate]                    DATETIMEOFFSET (7) NULL,
    [ExtensionDuration]               INT            NULL,
    [LateWalkBreachAlertEmployeeID]   INT            NULL,
    [MissedWalkBreachAlertUserID]     INT            NULL,
    [CheckpointBreachAlertUserID]     INT            NULL,
    [SkipCheckpointBreachAlertUserID] INT            NULL,
    [CreatedByUserID]                 INT            NOT NULL,
    [CreatedDate]                     DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]            INT            NULL,
    [ModifiedDate]                DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]                INT            NULL,
    [ArchivedDate]                    DATETIMEOFFSET (7) NULL,
    [DefaultHazardEmployeeID]         INT            NULL,
    PRIMARY KEY CLUSTERED ([WalkAssignmentID] ASC),
    CONSTRAINT [FK_WalkAssignment_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WalkAssignment_CheckpointBreachAlertUserID] FOREIGN KEY ([CheckpointBreachAlertUserID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WalkAssignment_DefaultHazardEmployeeID] FOREIGN KEY ([DefaultHazardEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_EmployeeID] FOREIGN KEY ([EmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_LateWalkBreachAlertEmployeeID] FOREIGN KEY ([LateWalkBreachAlertEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_ManagerSignatureID] FOREIGN KEY ([ManagerSignatureID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_MissedWalkBreachAlertUserID] FOREIGN KEY ([MissedWalkBreachAlertUserID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WalkAssignment_SkipCheckpointBreachAlertUserID] FOREIGN KEY ([SkipCheckpointBreachAlertUserID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_WalkAssignment_TaskID] FOREIGN KEY ([TaskID]) REFERENCES [V7].[BSSTask] ([TaskID]),
    CONSTRAINT [FK_WalkAssignment_TaskScheduleID] FOREIGN KEY ([TaskScheduleID]) REFERENCES [V7].[TaskSchedule] ([TaskScheduleID]),
    CONSTRAINT [FK_WalkAssignment_WalkID] FOREIGN KEY ([WalkID]) REFERENCES [V7].[Walk] ([WalkID])
);

