CREATE TABLE [V7].[Walk] (
    [WalkID]                  INT            IDENTITY (1, 1) NOT NULL,
    [TagTypeID]               INT            NOT NULL,
    [WalkTemplateID]          INT            NULL,
    [UserAreaID]              INT            NOT NULL,
    [Reference]               NVARCHAR (100) NULL,
    [Title]                   NVARCHAR (255) NOT NULL,
    [Description]             NVARCHAR (MAX) NULL,
    [LocationID]              INT            NOT NULL,
    [Duration]                INT            NOT NULL,
    [IsOrdered]               BIT            DEFAULT ((1)) NOT NULL,
    [IsGPSTracked]            BIT            DEFAULT ((0)) NOT NULL,
    [IsSignOffRequired]       BIT            DEFAULT ((0)) NOT NULL,
    [IsPointWalk]             BIT            DEFAULT ((0)) NOT NULL,
    [MaxPreStartDuration]     INT            NULL,
    [MaxPostStartDuration]    INT            NULL,
    [MaxExtensionDuration]    INT            NULL,
    [IsAdhocAllowed]          BIT            DEFAULT ((0)) NOT NULL,
    [IsRandomImageRequired]   BIT            DEFAULT ((0)) NOT NULL,
    [RandomImageInstruction]  NVARCHAR (255) NULL,
    [IsRandomWalk]            BIT            DEFAULT ((0)) NOT NULL,
    [RandomWalkRangeMin]      INT            NULL,
    [RandomWalkRangeMax]      INT            NULL,
    [Version]                 INT            DEFAULT ((1)) NOT NULL,
    [OriginalWalkID]          INT            NULL,
    [CreatedByUserID]         INT            NOT NULL,
    [CreatedDate]             DATETIMEOFFSET (7) NOT NULL,
    [ModifiedByUserID]    INT            NULL,
    [ModifiedDate]        DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]        INT            NULL,
    [ArchivedDate]            DATETIMEOFFSET (7) NULL,
    [DefaultHazardEmployeeID] INT            NULL,
    PRIMARY KEY CLUSTERED ([WalkID] ASC),
    CONSTRAINT [FK_Walk_ArchivedBy] FOREIGN KEY ([ArchivedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Walk_CreatedBy] FOREIGN KEY ([CreatedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Walk_DefaultHazardEmployeeID] FOREIGN KEY ([DefaultHazardEmployeeID]) REFERENCES [V7].[Employee] ([EmployeeID]),
    CONSTRAINT [FK_Walk_LocationID] FOREIGN KEY ([LocationID]) REFERENCES [V7].[Location] ([LocationID]),
    CONSTRAINT [FK_Walk_ModifiedBy] FOREIGN KEY ([ModifiedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_Walk_OriginalWalkID] FOREIGN KEY ([OriginalWalkID]) REFERENCES [V7].[Walk] ([WalkID]),
    CONSTRAINT [FK_Walk_TagTypeID] FOREIGN KEY ([TagTypeID]) REFERENCES [V7].[TagType] ([TagTypeID]),
    CONSTRAINT [FK_Walk_UserAreaID] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID]),
    CONSTRAINT [FK_Walk_WalkTemplateID] FOREIGN KEY ([WalkTemplateID]) REFERENCES [V7].[WalkTemplate] ([WalkTemplateID])
);

