CREATE TABLE [V7].[WorkInstruction] (
    [WorkInstructionID]      INT                IDENTITY (1, 1) NOT NULL,
    [UserAreaID]             INT                NOT NULL,
    [SSOWDocumentTypeID]     INT                NOT NULL,
    [SSOWStatusTypeID]       INT                NOT NULL,
    [InstructionNumber]      NVARCHAR (50)      NOT NULL,
    [InstructionTitle]       NVARCHAR (255)     NOT NULL,
    [InstructionVersion]     NVARCHAR (20)      DEFAULT ('1.0') NULL,
    [PreviousVersionID]      INT                NULL,
    [IsCurrentVersion]       BIT                DEFAULT ((1)) NULL,
    [TaskDescription]        NVARCHAR (MAX)     NOT NULL,
    [DetailedInstructions]   NVARCHAR (MAX)     NOT NULL,
    [Prerequisites]          NVARCHAR (MAX)     NULL,
    [RequiredEquipment]      NVARCHAR (MAX)     NULL,
    [RequiredMaterials]      NVARCHAR (MAX)     NULL,
    [RequiredTools]          NVARCHAR (MAX)     NULL,
    [SafetyRequirements]     NVARCHAR (MAX)     NULL,
    [HazardWarnings]         NVARCHAR (MAX)     NULL,
    [RequiredPPE]            NVARCHAR (500)     NULL,
    [QualityStandards]       NVARCHAR (MAX)     NULL,
    [InspectionRequirements] NVARCHAR (MAX)     NULL,
    [AcceptanceCriteria]     NVARCHAR (MAX)     NULL,
    [EstimatedDuration]      INT                NULL,
    [PersonnelRequired]      INT                DEFAULT ((1)) NULL,
    [SkillLevelRequired]     NVARCHAR (100)     NULL,
    [AuthorUserID]           INT                NOT NULL,
    [ReviewerUserID]         INT                NULL,
    [ApproverUserID]         INT                NULL,
    [ReviewDate]             DATETIMEOFFSET (7) NULL,
    [ApprovalDate]           DATETIMEOFFSET (7) NULL,
    [NextReviewDate]         DATETIMEOFFSET (7) NULL,
    [PublishedDate]          DATETIMEOFFSET (7) NULL,
    [PublishedByUserID]      INT                NULL,
    [EffectiveDate]          DATETIMEOFFSET (7) NULL,
    [ExpiryDate]             DATETIMEOFFSET (7) NULL,
    [IsActive]               BIT                DEFAULT ((1)) NULL,
    [CreatedByUserID]        INT                NOT NULL,
    [CreatedDate]            DATETIMEOFFSET (7) DEFAULT (sysdatetimeoffset()) NOT NULL,
    [ModifiedByUserID]   INT                NULL,
    [ModifiedDate]       DATETIMEOFFSET (7) NULL,
    [ArchivedByUserID]       INT                NULL,
    [ArchivedDate]           DATETIMEOFFSET (7) NULL,
    PRIMARY KEY CLUSTERED ([WorkInstructionID] ASC),
    CONSTRAINT [FK_WorkInstruction_Approver] FOREIGN KEY ([ApproverUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WorkInstruction_Author] FOREIGN KEY ([AuthorUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WorkInstruction_DocumentType] FOREIGN KEY ([SSOWDocumentTypeID]) REFERENCES [V7].[SSOWDocumentType] ([SSOWDocumentTypeID]),
    CONSTRAINT [FK_WorkInstruction_PreviousVersion] FOREIGN KEY ([PreviousVersionID]) REFERENCES [V7].[WorkInstruction] ([WorkInstructionID]),
    CONSTRAINT [FK_WorkInstruction_Publisher] FOREIGN KEY ([PublishedByUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WorkInstruction_Reviewer] FOREIGN KEY ([ReviewerUserID]) REFERENCES [V7].[User] ([UserID]),
    CONSTRAINT [FK_WorkInstruction_Status] FOREIGN KEY ([SSOWStatusTypeID]) REFERENCES [V7].[SSOWStatusType] ([SSOWStatusTypeID]),
    CONSTRAINT [FK_WorkInstruction_UserArea] FOREIGN KEY ([UserAreaID]) REFERENCES [V7].[UserArea] ([UserAreaID])
);

